import { Italiana, Jost } from "next/font/google";
import "./globals.css";


// Import the Italiana font
const jost = Jost({ subsets: ["latin"], display: "swap",  });
const italiana = Italiana({ subsets: ["latin"], weight:["400"] });

export const metadata = {
  title: "Martha Batiz | Author",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost.className}`}>
        {children}
      </body>
    </html>
  );
}
